main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.18"
author: rndtrash
description: A simple MOTD plugin
commands:
  motd:
    description: Show the message of the day
    usage: /motd
  first:
    description: Show the message that newbies get on their first join
    usage: /first